/**
 * IndexedDB schema + memoized connection (idb v8).
 *
 * DB 'knowledge-nebula', version 1, four stores:
 * - documents:  contentHash -> parsed doc (DocNode snapshot, full text, chunk texts)
 * - embeddings: contentHash -> Float32Array vectors, stored natively (no base64
 *   round-trip — this is what makes the <3s session restore possible)
 * - graphs:     corpusHash  -> GraphExport + settled layout positions
 * - settings:   string      -> small values (e.g. 'lastCorpusHash')
 */

import { openDB, type DBSchema, type IDBPDatabase } from 'idb';
import type { DocNode, GraphExport } from '../model/types';

export const DB_NAME = 'knowledge-nebula';
export const DB_VERSION = 2;

export interface DocumentRecord {
  hash: string;
  node: DocNode;
  text: string;
  chunkTexts: string[];
  /** Markdown link targets — absent on records written before this field existed. */
  mdLinkTargets?: string[];
}

export interface EmbeddingRecord {
  hash: string;
  /** zero-length = absent */
  docVector: Float32Array;
  /** flattened [nChunks * EMBED_DIMS]; zero-length = absent */
  chunkVectors: Float32Array;
  nChunks: number;
}

export interface GraphRecord {
  corpusHash: string;
  exportData: GraphExport;
  positions: Record<string, [number, number, number]>;
  savedAt: number;
}

export interface SnapshotRecord {
  id?: number; // auto-generated by IndexedDB
  name: string;
  savedAt: number; // Date.now()
  corpusHash: string;
  docHashes: string[]; // references into documents + embeddings stores
  exportData: GraphExport;
  positions: Record<string, [number, number, number]>;
}

export interface NebulaDB extends DBSchema {
  documents: { key: string; value: DocumentRecord };
  embeddings: { key: string; value: EmbeddingRecord };
  graphs: { key: string; value: GraphRecord };
  settings: { key: string; value: unknown };
  snapshots: { key: number; value: SnapshotRecord; indexes: { 'by-savedAt': number } };
}

let dbPromise: Promise<IDBPDatabase<NebulaDB>> | null = null;

/**
 * Close the memoized DB connection (if any). Call this before an upgrade
 * is expected — e.g. during HMR — so the new version can proceed without
 * being blocked by the stale connection.
 */
export async function closeDb(): Promise<void> {
  if (!dbPromise) return;
  try {
    const db = await dbPromise;
    db.close();
  } catch {
    /* already failed / closed — fine */
  } finally {
    dbPromise = null;
  }
}

/** Memoized connection. Rejections drop the memo so later calls may retry. */
export function getDb(): Promise<IDBPDatabase<NebulaDB>> {
  if (dbPromise) return dbPromise;
  const p = openDB<NebulaDB>(DB_NAME, DB_VERSION, {
    upgrade(db, oldVersion) {
      if (oldVersion < 1) {
        db.createObjectStore('documents', { keyPath: 'hash' });
        db.createObjectStore('embeddings', { keyPath: 'hash' });
        db.createObjectStore('graphs', { keyPath: 'corpusHash' });
        db.createObjectStore('settings'); // out-of-line string keys
      }
      if (oldVersion < 2) {
        const snapStore = db.createObjectStore('snapshots', {
          keyPath: 'id',
          autoIncrement: true,
        });
        snapStore.createIndex('by-savedAt', 'savedAt');
      }
    },
    blocked() {
      // An older connection (e.g. from a pre-HMR module) is still open.
      // We can't force-close it from here, so log a warning. The timeout
      // below will reject the promise so callers degrade gracefully.
      console.warn(
        '[knowledge-nebula] DB upgrade blocked by an older connection — ' +
          'reload the page if persistence is stuck.',
      );
    },
    blocking() {
      // *This* connection is blocking a newer version from opening
      // (e.g. after a second HMR). Close ourselves to unblock.
      dbPromise?.then((db) => db.close()).catch(() => {});
      dbPromise = null;
    },
    terminated() {
      // abnormal close (not db.close()) — allow a clean reopen next call
      dbPromise = null;
    },
  });

  // Safety timeout: if the upgrade is blocked for >2s, reject so callers
  // degrade to no-cache instead of hanging forever.
  const guarded = Promise.race([
    p,
    new Promise<never>((_, reject) =>
      setTimeout(
        () => reject(new Error('DB open timed out (upgrade likely blocked)')),
        2000,
      ),
    ),
  ]);

  dbPromise = guarded;
  guarded.catch(() => {
    // private mode / quota / blocked upgrade: callers degrade to no-cache;
    // clearing the memo lets a later call retry.
    if (dbPromise === guarded) dbPromise = null;
  });
  return guarded;
}
