/**
 * IndexedDB schema + memoized connection (idb v8).
 *
 * DB 'knowledge-nebula', version 5, eight stores:
 * - documents:  contentHash -> parsed doc (DocNode snapshot, full text, chunk texts)
 * - embeddings: contentHash -> Float32Array vectors, stored natively (no base64
 *   round-trip — this is what makes the <3s session restore possible)
 * - graphs:     corpusHash  -> GraphExport + settled layout positions
 * - settings:   string      -> small values (e.g. 'lastCorpusHash')
 * - snapshots:  autoIncrement -> named GraphExport snapshots (v2), indexed by savedAt
 * - originals:  contentHash -> the exact ingested file bytes as a Blob (v3), so
 *   "Open" can hand back the byte-identical original (never leaves the browser)
 * - chats:      stable corpus id -> local transcript (v4)
 * - corpora:    stable corpus id -> named, independently restorable workspace (v5)
 */

import { openDB, type DBSchema, type IDBPDatabase } from 'idb';
import type { DocNode, GraphExport, LinkRef } from '../model/types';

export const DB_NAME = 'knowledge-nebula';
export const DB_VERSION = 5;

export interface DocumentRecord {
  hash: string;
  node: DocNode;
  text: string;
  chunkTexts: string[];
  /** Markdown link targets — absent on records written before this field existed. */
  mdLinkTargets?: string[];
  /** Labelled links (label ↔ url) for the reader — absent on older records. */
  docLinks?: LinkRef[];
}

export interface EmbeddingRecord {
  hash: string;
  /** Embedding model + preprocessing profile that produced these vectors. */
  fingerprint?: string;
  /** zero-length = absent */
  docVector: Float32Array;
  /** flattened [nChunks * EMBED_DIMS]; zero-length = absent */
  chunkVectors: Float32Array;
  nChunks: number;
}

export interface GraphRecord {
  corpusHash: string;
  exportData: GraphExport;
  positions: Record<string, [number, number, number]>;
  savedAt: number;
}

export interface SnapshotRecord {
  id?: number; // auto-generated by IndexedDB
  name: string;
  savedAt: number; // Date.now()
  corpusHash: string;
  docHashes: string[]; // references into documents + embeddings stores
  exportData: GraphExport;
  positions: Record<string, [number, number, number]>;
  /** Stable workspace id; absent on snapshots created before multi-corpus support. */
  corpusId?: string;
}

export interface OriginalFileRecord {
  hash: string;
  /** Original filename (with extension) — the download name on "Open". */
  name: string;
  /** Exact ingested bytes; Blob.type carries the MIME. */
  blob: Blob;
}

/** Transcript scoped to one corpus, retained entirely on-device. */
export interface ChatRecord {
  corpusHash: string;
  messages: import('../store/chatStore').ChatMessage[];
  savedAt: number;
}

export interface WatchedFileRecord {
  size: number;
  lastModified: number;
  docId: string;
}

/** A persisted directory source. Handles are structured-cloneable in supporting browsers. */
export interface WatchedFolderRecord {
  handle: FileSystemDirectoryHandle;
  rootName: string;
  files: Record<string, WatchedFileRecord>;
  paused: boolean;
}

/**
 * Stable workspace identity. `corpusHash` remains the content revision and can
 * change after every add/remove; the UUID `id` is what names and switches a
 * corpus without turning every revision into a separate workspace.
 */
export interface CorpusRecord {
  id: string;
  name: string;
  createdAt: number;
  updatedAt: number;
  corpusHash: string | null;
  docHashes: string[];
  exportData: GraphExport | null;
  positions: Record<string, [number, number, number]>;
  watch?: WatchedFolderRecord;
}

export interface NebulaDB extends DBSchema {
  documents: { key: string; value: DocumentRecord };
  embeddings: { key: string; value: EmbeddingRecord };
  graphs: { key: string; value: GraphRecord };
  settings: { key: string; value: unknown };
  snapshots: { key: number; value: SnapshotRecord; indexes: { 'by-savedAt': number } };
  originals: { key: string; value: OriginalFileRecord };
  chats: { key: string; value: ChatRecord };
  corpora: {
    key: string;
    value: CorpusRecord;
    indexes: { 'by-updatedAt': number };
  };
}

let dbPromise: Promise<IDBPDatabase<NebulaDB>> | null = null;

/**
 * Close the memoized DB connection (if any). Call this before an upgrade
 * is expected — e.g. during HMR — so the new version can proceed without
 * being blocked by the stale connection.
 */
export async function closeDb(): Promise<void> {
  if (!dbPromise) return;
  try {
    const db = await dbPromise;
    db.close();
  } catch {
    /* already failed / closed — fine */
  } finally {
    dbPromise = null;
  }
}

/** Memoized connection. Rejections drop the memo so later calls may retry. */
export function getDb(): Promise<IDBPDatabase<NebulaDB>> {
  if (dbPromise) return dbPromise;
  // Declared before openDB so the blocked() callback below can never observe
  // it in the temporal dead zone; assigned when the guard promise is built.
  let failIfStillBlocked: (() => void) | undefined;
  const p = openDB<NebulaDB>(DB_NAME, DB_VERSION, {
    upgrade(db, oldVersion) {
      if (oldVersion < 1) {
        db.createObjectStore('documents', { keyPath: 'hash' });
        db.createObjectStore('embeddings', { keyPath: 'hash' });
        db.createObjectStore('graphs', { keyPath: 'corpusHash' });
        db.createObjectStore('settings'); // out-of-line string keys
      }
      if (oldVersion < 2) {
        const snapStore = db.createObjectStore('snapshots', {
          keyPath: 'id',
          autoIncrement: true,
        });
        snapStore.createIndex('by-savedAt', 'savedAt');
      }
      if (oldVersion < 3) {
        db.createObjectStore('originals', { keyPath: 'hash' });
      }
      if (oldVersion < 4) {
        db.createObjectStore('chats', { keyPath: 'corpusHash' });
      }
      if (oldVersion < 5) {
        const corpusStore = db.createObjectStore('corpora', { keyPath: 'id' });
        corpusStore.createIndex('by-updatedAt', 'updatedAt');
      }
    },
    blocked() {
      // An older connection (e.g. from a pre-HMR module) is still open.
      // We can't force-close it from here, so warn and start the short fuse
      // below — this is the case that genuinely never resolves on its own.
      console.warn(
        '[knowledge-nebula] DB upgrade blocked by an older connection — ' +
          'reload the page if persistence is stuck.',
      );
      failIfStillBlocked?.();
    },
    blocking() {
      // *This* connection is blocking a newer version from opening
      // (e.g. after a second HMR). Close ourselves to unblock.
      dbPromise?.then((db) => db.close()).catch(() => {});
      dbPromise = null;
    },
    terminated() {
      // abnormal close (not db.close()) — allow a clean reopen next call
      dbPromise = null;
    },
  });

  // Two different failure shapes, two different fuses.
  //
  // A *blocked* upgrade never completes on its own, so it gets the short fuse —
  // but only once blocked() actually fires. A merely slow open (cold profile,
  // contended disk, a first v1→v5 upgrade over a large database) does finish,
  // and the old unconditional 2s race declared "persistence unavailable" for
  // the whole visit while the open was still healthy and in progress. The long
  // fuse only guards against a pathological hang.
  let timedOut = false;
  const guarded = Promise.race([
    p,
    new Promise<never>((_, reject) => {
      const fail = (message: string) => () => {
        timedOut = true;
        reject(new Error(message));
      };
      failIfStillBlocked = () => {
        setTimeout(fail('DB open timed out (upgrade blocked by an older connection)'), 2000);
      };
      setTimeout(fail('DB open timed out'), 20_000);
    }),
  ]);

  dbPromise = guarded;
  guarded.catch(() => {
    // private mode / quota / blocked upgrade: callers degrade to no-cache;
    // clearing the memo lets a later call retry.
    if (dbPromise === guarded) dbPromise = null;
  });

  // If the timeout won the race, `p` (the real open request) may still
  // resolve later — e.g. the blocking connection above eventually closes on
  // its own. Nothing else holds a reference to that connection once
  // `guarded` already rejected to every caller, so it would otherwise leak
  // an open IDB connection for the life of the tab. Close it the moment it
  // shows up; `p`'s own rejection path is already handled by `guarded` above.
  p.then((db) => {
    if (timedOut) db.close();
  }).catch(() => {});

  return guarded;
}
