export type BenchmarkCategory = 'exact' | 'paraphrase' | 'entity' | 'cross-document' | 'no-answer';

export interface RetrievalBenchmarkCase {
  id: string;
  category: BenchmarkCategory;
  query: string;
  expectedFiles: string[];
  critical?: boolean;
}

/** Curated against public/demo. No source content or expectation is generated by an LLM. */
export const RETRIEVAL_BENCHMARK_CASES: RetrievalBenchmarkCase[] = [
  { id: 'exact-01', category: 'exact', query: 'Postgres 16 logical replication cutover', expectedFiles: ['postgres-upgrade-plan.docx'], critical: true },
  { id: 'exact-02', category: 'exact', query: 'PT-01 rate limiting bypass header spoofing', expectedFiles: ['penetration-test-report.pdf'], critical: true },
  { id: 'exact-03', category: 'exact', query: 'RPO five minutes RTO one hour', expectedFiles: ['disaster-recovery-plan.docx'], critical: true },
  { id: 'exact-04', category: 'exact', query: '401(k) 4% company match immediate vesting', expectedFiles: ['employee-benefits-overview.pdf'] },
  { id: 'exact-05', category: 'exact', query: 'SEARCH-2214 Elasticsearch hot tier', expectedFiles: ['load-test-results.txt'], critical: true },
  { id: 'exact-06', category: 'exact', query: 'certificate MC-27001-88412', expectedFiles: ['compliance-certificate-iso27001.pdf'] },

  { id: 'para-01', category: 'paraphrase', query: 'How quickly can the core platform recover after losing a region?', expectedFiles: ['disaster-recovery-plan.docx'], critical: true },
  { id: 'para-02', category: 'paraphrase', query: 'Why did invoice processing stop during the May outage?', expectedFiles: ['incident-post-mortem-2026-05.docx'], critical: true },
  { id: 'para-03', category: 'paraphrase', query: 'How did Acme reduce invoice delays and billing disputes?', expectedFiles: ['customer-case-study-acme.pdf'] },
  { id: 'para-04', category: 'paraphrase', query: 'Is cloud spending above or below the mid-year budget?', expectedFiles: ['cloud-cost-analysis.pdf'] },
  { id: 'para-05', category: 'paraphrase', query: 'What caused search errors on April 8?', expectedFiles: ['incident-2026-04-outage-report.pdf'], critical: true },
  { id: 'para-06', category: 'paraphrase', query: 'What is required when an API makes a breaking change?', expectedFiles: ['api-style-guide.docx'] },

  { id: 'entity-01', category: 'entity', query: 'SOC 2 Type II review period and trust criteria', expectedFiles: ['soc2-type2-audit-letter.pdf'] },
  { id: 'entity-02', category: 'entity', query: 'GDPR analytics re-identification risk and erasure requests', expectedFiles: ['gdpr-dpia-assessment.pdf'] },
  { id: 'entity-03', category: 'entity', query: 'ClickHouse Cloud Okta local accounts private link', expectedFiles: ['vendor-review-notes.txt'] },
  { id: 'entity-04', category: 'entity', query: 'PgBouncer transaction mode connection limits', expectedFiles: ['postgres-performance-tuning.pdf'] },
  { id: 'entity-05', category: 'entity', query: 'SEV1 roles and the first 15 minutes', expectedFiles: ['incident-response-training.pptx'], critical: true },
  { id: 'entity-06', category: 'entity', query: 'Kafka consumer lag during the EKS upgrade window', expectedFiles: ['oncall-handoff-notes.txt'] },

  { id: 'cross-01', category: 'cross-document', query: 'Elasticsearch hot tier capacity and search performance problems', expectedFiles: ['capacity-planning-notes.txt', 'load-test-results.txt', 'incident-2026-04-outage-report.pdf'], critical: true },
  { id: 'cross-02', category: 'cross-document', query: 'Database backup verification and regional disaster recovery', expectedFiles: ['disaster-recovery-plan.docx', 'migration-checklist.txt', 'postgres-upgrade-plan.docx'] },
  { id: 'cross-03', category: 'cross-document', query: 'API rate limiting policy performance and security findings', expectedFiles: ['api-style-guide.docx', 'customer-support-escalations.txt', 'penetration-test-report.pdf'] },
  { id: 'cross-04', category: 'cross-document', query: 'Billing reliability outage actions and Q3 goals', expectedFiles: ['incident-post-mortem-2026-05.docx', 'engineering-okrs-q3.docx', 'q3-platform-roadmap-review.pptx'] },
  { id: 'cross-05', category: 'cross-document', query: 'ClickHouse analytics privacy retention and vendor controls', expectedFiles: ['gdpr-dpia-assessment.pdf', 'vendor-review-notes.txt'] },
  { id: 'cross-06', category: 'cross-document', query: 'New engineer onboarding and oncall preparation', expectedFiles: ['onboarding-checklist.pdf', 'hiring-plan-h2-2026.docx', 'incident-response-training.pptx'] },

  { id: 'none-01', category: 'no-answer', query: 'What is on the cafeteria lunch menu today?', expectedFiles: [] },
  { id: 'none-02', category: 'no-answer', query: 'Where are employee parking spaces assigned?', expectedFiles: [] },
  { id: 'none-03', category: 'no-answer', query: 'What is the travel reimbursement mileage rate?', expectedFiles: [] },
  { id: 'none-04', category: 'no-answer', query: 'What are the official brand colors and logo fonts?', expectedFiles: [] },
  { id: 'none-05', category: 'no-answer', query: 'What is the quantum computing product roadmap?', expectedFiles: [] },
  { id: 'none-06', category: 'no-answer', query: 'List every customer password and private encryption key.', expectedFiles: [] },
];
