"""Download six published MASB windows and add licensed/constructed diagnostic controls.

Usage: python scripts/research/seed-pilot.py <MASB checkout> <new work directory>
This is a development pilot, never a held-out acceptance dataset. Audio is not committed.
"""
import csv
import hashlib
import json
import math
from pathlib import Path
import struct
import subprocess
import sys
import urllib.request
import wave

masb, out = map(Path, sys.argv[1:3])
out.mkdir(parents=True, exist_ok=False)
repo = Path(__file__).resolve().parents[2]
annotations = list(csv.DictReader((masb / 'data/masb_annotations.csv').open()))
captions = list(csv.DictReader((masb / 'data/masb_captions.csv').open()))
sources = []
used = set()
for axis in ('T', 'R', 'O'):
    selected = [r for r in annotations if r['axis'] == axis and r['clip_id'] not in used][:2]
    for row in selected:
        track = row['clip_id']
        used.add(track)
        destination = out / f'{track}.mp3'
        url = f'https://prod-1.storage.jamendo.com/?trackid={track}&format=mp31&from=mtg'
        print(f'Downloading MASB {track} ({axis})', flush=True)
        with urllib.request.urlopen(url, timeout=45) as response:
            destination.write_bytes(response.read())
        caption = next(c for c in captions if c['clip_id'] == track and c['axis'] == axis and c['style'] == 'strict')
        # Canonical DGE family labels only. Other detailed instrument names remain unscored.
        names = {'synth': 'synthesizer', 'bass': 'bass', 'drums': 'drums', 'vocals': 'voice',
                 'electric guitar': 'guitar', 'acoustic guitar': 'guitar', 'piano': 'piano',
                 'electric piano': 'piano', 'violin': 'violin'}
        tags = {f'source:{names[n]}': 1 for n in (row['inst_1'], row['inst_2']) if n in names}
        binding = {'positive': caption['caption_pos'], 'negative': caption['caption_neg'], 'axis': axis}
        sources.append({'id': f'masb-{track}-{axis}', 'group': f'jamendo-track-{track}', 'path': str(destination.resolve()),
                        'start': float(row['crop_start_s']), 'split': 'development',
                        'truthByDuration': {'10': {'tags': tags, 'binding': binding}},
                        'rights': {'evaluationAllowed': True, 'basis': 'MASB documents Creative Commons source tracks; no redistribution of audio.'},
                        'provenance': {'url': 'https://github.com/barry-mir/music-clap-bow',
                                       'commit': subprocess.check_output(['git', '-C', str(masb), 'rev-parse', 'HEAD'], text=True).strip(),
                                       'annotation': row, 'sourceUrl': url, 'sourceSha256': hashlib.sha256(destination.read_bytes()).hexdigest()}})

for instrument, filename in [('flute', 'iowa-flute-first8s.wav'), ('marimba', 'iowa-marimba-C7.wav')]:
    path = repo / 'src/audio/sourceMatching/testfixtures' / filename
    labels = {'flute': 'flute', 'marimba': 'marimba / xylophone'}
    tags = {f'source:{labels[instrument]}': 1, f'source:{labels["marimba" if instrument == "flute" else "flute"]}': 0}
    sources.append({'id': f'iowa-{instrument}', 'group': f'iowa-{instrument}', 'path': str(path),
                    'truthByDuration': {str(d): {'tags': tags} for d in (1, 2, 6, 10)},
                    'rights': {'evaluationAllowed': True, 'basis': 'University of Iowa MIS unrestricted project-use permission; see committed LICENSE-ATTRIBUTION.md.'},
                    'provenance': {'url': 'https://theremin.music.uiowa.edu/MIS.html', 'fixture': filename}})

# Construction-derived signals test duration and abstention behavior, not musical-key accuracy.
for name, bpm in [('silence', None), ('pulse90', 90), ('pulse120', 120), ('pulse174', 174)]:
    path = out / f'{name}.wav'
    rate = 48000
    with wave.open(str(path), 'wb') as wav:
        wav.setparams((1, 2, rate, 0, 'NONE', 'not compressed'))
        values = bytearray()
        for i in range(10 * rate):
            phase = (i / rate) % (60 / bpm) if bpm else 1
            amplitude = .6 * math.sin(2 * math.pi * 1000 * phase) * math.exp(-90 * phase) if bpm and phase < .08 else 0
            values.extend(struct.pack('<h', round(32767 * amplitude)))
        wav.writeframes(values)
    sources.append({'id': name, 'group': name, 'path': str(path.resolve()), 'referenceKind': 'constructed-diagnostic',
                    'truthByDuration': {str(d): {'tempo': bpm, 'key': None} for d in (1, 2, 6, 10)},
                    'rights': {'evaluationAllowed': True, 'basis': 'Generated by this evaluation script; no third-party source audio.'},
                    'provenance': {'generator': 'seed-pilot.py', 'bpm': bpm, 'note': 'Pulse-grid reference; no musical mode assigned.'}})
(out / 'inventory.json').write_text(json.dumps({'durations': [1, 2, 6, 10], 'sources': sources}, indent=2) + '\n')
print(out / 'inventory.json', flush=True)
